# Generated by Django 5.0.7 on 2024-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_wine_producer_wine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
